routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//  Site Routes
Route::get('/', 'HomeController@index')->name('home');
Route::post('/comment', 'HomeController@comment')->name('comment');
// Search Route
Route::get('/search', 'HomeController@search')->name('search');


Route::namespace('Site')->group(function () {
    Route::get('/articles', 'ArticleController@index')->name('articles');
    Route::get('/article/{articleSlug}', 'ArticleController@single')->name('articles.show');
    Route::get('/courses', 'CourseController@index')->name('courses');
    Route::get('/course/{courseSlug}', 'CourseController@single')->name('courses.show');
    Route::get('/categories', 'CategoryController@index')->name('categories');
    Route::get('/categories/{categoryName}', 'CategoryController@single')->name('categories.show');
    Route::get('/active/email/{token}', 'ActivationCodeController@active')->name('active.email');


    // Download Route
    Route::get('/download/{episode}', 'CourseController@download');

    //Sitemap Routes
    Route::prefix('sitemap')->group(function () {
        Route::get('/', 'SitemapController@index');
        Route::get('/course', 'SitemapController@course');
        Route::get('/article', 'SitemapController@article');
        Route::get('/episode', 'SitemapController@episode');
    });
    //Feed - RSS Routes
    Route::prefix('feed')->group(function () {
        Route::get('/course', 'SitemapController@course');
        Route::get('/article', 'SitemapController@article')->name('feed.article');
        Route::get('/episode', 'SitemapController@episode');
    });

    //Payment Routes
    Route::post('/course/payment', 'PaymentController@payment')->name('course.payment');
    Route::get('/course/payment/checker', 'PaymentController@checker')->name('course.payment.checker');

    Route::get('/active', 'ActivationCodeController@jobs');
});

//User Routes
Route::namespace('UserPanel')->prefix('user')->middleware('auth')->group(function () {
    Route::get('/', 'UserPanelController@index')->name('user.panel.index');
    Route::get('/history', 'UserPanelController@history')->name('user.panel.history');
    Route::get('/vip', 'UserPanelController@vip')->name('user.panel.vip');

    Route::post('/payment', 'UserPanelController@payment')->name('user.panel.payment');
    Route::get('/payment/checker', 'UserPanelController@checker')->name('user.panel.checker');

});


//  Panel Routes
Route::namespace('Panel')->middleware('CheckAdmin')->prefix('admin')->group(function () {
    Route::get('/', 'PanelController@index')->name('panel');
    Route::post('/upload-image', 'PanelController@ckImageUploader');
    Route::resource('/articles', 'ArticleController');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/courses', 'CourseController');
    Route::resource('/episodes', 'EpisodeController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/permissions', 'PermissionController');
    Route::resource('/levels', 'LevelController')->parameters(['levels' => 'user']);
    Route::resource('/comments', 'CommentController')->except(['index', 'create', 'store', 'show']);
    Route::get('/comments/approved', 'CommentController@approved')->name('comments.approved');
    Route::get('/comments/unapproved', 'CommentController@unapproved')->name('comments.unapproved');
    Route::any('/comments/reject/{comment}', 'CommentController@reject')->name('comments.reject');


    Route::prefix('users')->group(function () {
        Route::get('/', 'UserController@index')->name('users.index');
        Route::get('/profile/{user}', 'UserController@profile')->name('users.profile');
        Route::get('/edit/{user}', 'UserController@edit')->name('users.edit');
        Route::put('/update/{user}', 'UserController@update')->name('users.update');
        Route::delete('/destroy/{user}', 'UserController@destroy')->name('users.destroy');
    });
});

//Auth::routes();
Route::namespace('Auth')->group(function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');

    //  Socialite Package --  Github
    Route::get('login/github', 'LoginController@redirectToProviderGithub')->name('login.github');
    Route::get('login/github/callback', 'LoginController@handleProviderCallbackGithub');

    //  Socialite Package --  Google
    Route::get('login/google', 'LoginController@redirectToProvider')->name('login.google');
    Route::get('login/google/callback', 'LoginController@handleProviderCallback');
});



//Route::get('/home', 'HomeController@index');

app/Http/Controllers/Panel/ArticleController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Http\Requests\Panel\ArticleRequest;
use App\Model\Article;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class ArticleController extends PanelController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $articles = Article::with('user')->latest()->paginate(20);
//        return response()->json(['articles'=>$articles , 'status'=>200],200);
        return view('/Panel.Articles.ArticleList', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('/Panel.Articles.NewArticle');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticleRequest $request
     * @return array
     */
    public function store(ArticleRequest $request)
    {
        Auth::loginUsingId(1);
        $imagesUrl = $this->imgUploader($request->file('imgsUrl'), 'Articles');
        auth()->user()->article()->create(array_merge([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'body' => $request->input('body'),
            'tag' => $request->input('tag'),
            'time' => $request->input('time'),
            'visibility' => $request->input('visibility'),
            'imgsUrl' => $imagesUrl]));
        return redirect(route('articles.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Article $article
     * @return void
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Article $article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Article $article)
    {
        return view('/Panel.Articles.EditArticle', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ArticleRequest $request
     * @param  \App\Model\Article $article
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(ArticleRequest $request, Article $article)
    {
        $files=$article->imgsUrl;
        if ($request->hasFile('imgsUrl')) {
            if ($files) {
                $this->imgDelete($files['imgsUrl']);
            }
            $imagesUrl = $this->imgUploader($request->file('imgsUrl'), 'Articles');
            $article->update(array_merge(['imgsUrl' => $imagesUrl]));
        }
        $article->update(array_merge([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'body' => $request->input('body'),
            'tag' => $request->input('tag'),
            'time' => $request->input('time'),
            'visibility' => $request->input('visibility'),
        ]));
        return redirect(route('articles.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Article $article
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function destroy(Article $article)
    {
        $files=$article->imgsUrl;
        if ($files) {
            $this->imgDelete($files['imgsUrl']);
        }
        $article->delete();
        return redirect(route('articles.index'));
    }
}

app/Http/Controllers/Panel/CategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Model\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $categories = Category::with('parent')->paginate(20);
        return view('/Panel.Categories.CategoryList', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::all();
        return view('/Panel.Categories.NewCategory', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        Category::create([
            'category_name' => $request->input('category_name'),
            'parent_id' => $request->input('parent_id'),
            'subject' => $request->input('subject'),
            'visibility' => $request->input('visibility'),
        ]);
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Model\Category $category
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Model\Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::where([
            ['id', '!=', $category->id],
            ['subject', $category->subject]
        ])->get();
        return view('/Panel.Categories.EditCategory', compact('categories', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Model\Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update([
            'category_name' => $request->input('category_name'),
            'parent_id' => $request->input('parent_id'),
            'subject' => $request->input('subject'),
            'visibility' => $request->input('visibility'),
        ]);
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Model\Category $category
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect(route('categories.index'));
    }
}

app/Http/Controllers/Panel/CommentController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Model\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function approved()
    {
        $approvedComments = Comment::whereVisibility('show')->with('commentable')->get();
        return view('Panel.Comments.CommentList', compact('approvedComments'));
    }

    public function unapproved()
    {
        $unapprovedComments = Comment::where('visibility', 'hidden')->get();
        return view('Panel.Comments.UnapprovedCommentList', compact('unapprovedComments'));
    }

    public function edit(Comment $comment)
    {
        //
    }

    public function update(Request $request,Comment $comment)
    {
        $comment->update(['visibility' => 'show']);
        $comment->commentable->increment('commentCount');
        return redirect()->back();
    }

    public function reject(Request $request, Comment $comment)
    {
        $comment->update(['visibility' => 'hidden']);
        $comment->commentable->decrement('commentCount');
        return redirect()->back();
    }

    public function destroy(Comment $comment)
    {
        $comment->commentable->decrement('commentCount');
        $comment->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Panel/EpisodeController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Http\Requests\Panel\EpisodeRequest;
use App\Model\Course;
use App\Model\Episode;
use Illuminate\Http\Request;

class EpisodeController extends PanelController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $episodes=Episode::with('course')->latest()->paginate(20);
        return view('/Panel.Episodes.EpisodeList',compact('episodes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses=Course::all();
        return view('/Panel.Episodes.NewEpisode',compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param EpisodeRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(EpisodeRequest $request)
    {
        $episode=Episode::create([
            'course_id'=>$request->input('course_id'),
            'title'=>$request->input('title'),
            'description'=>$request->input('description'),
            'type'=>$request->input('type'),
            'tag'=>$request->input('tag'),
            'fileUrl'=>$request->input('fileUrl'),
            'time'=>$request->input('time'),
            'number'=>$request->input('number'),
        ]);
        $this->setCourseTime($episode);
        return redirect(route('episodes.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param Episode $episode
     * @return void
     */
    public function show(Episode $episode)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Episode $episode
     * @return \Illuminate\Http\Response
     */
    public function edit(Episode $episode)
    {
        $courses=Course::all();
        return view('/Panel.Episodes.EditEpisode',compact('episode','courses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EpisodeRequest $request
     * @param Episode $episode
     * @return \Illuminate\Http\Response
     */
    public function update(EpisodeRequest $request, Episode $episode)
    {
        $episode->update([
            'course_id'=>$request->input('course_id'),
            'title'=>$request->input('title'),
            'description'=>$request->input('description'),
            'type'=>$request->input('type'),
            'tag'=>$request->input('tag'),
            'fileUrl'=>$request->input('fileUrl'),
            'time'=>$request->input('time'),
            'number'=>$request->input('number'),
        ]);
        $this->setCourseTime($episode);
        return redirect(route('episodes.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Episode $episode
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Episode $episode)
    {
        $episode->delete();
        return redirect(route('episodes.index'));
    }
}

resources/views/Panel/Roles/EditRole.blade.php
@extends('layouts.panel-master')
@section('title','ویرایش سمت')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            ویرایش سمت {{$role->role_name}}
        </header>
        <div class="panel-body">
            <form class="form-horizontal tasi-form" method="POST" action="{{route('roles.update',['role'=>$role->id])}}"
                  enctype="multipart/form-data">
                {{csrf_field()}}
                {{method_field('PUT')}}
                @include('errors.errors')
                <div class="form-group">
                    <label class="col-sm-2 control-label">عنوان سمت :</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control round-input" name="role_name"
                               value="{{$role->role_name}}">
                    </div>

                    <label class="col-sm-2 control-label"> دسترسی ها :</label>
                    <div class="col-sm-4">
                        <select name="permissions[]" class="form-control round-input permissions" multiple>
                            <option value="0" disabled>انتخاب کنید ...</option>
                            @foreach($permissions as $permission)
                                <option value="{{$permission->id}}" {{in_array(trim($permission->id), $role->permission->pluck('id')->toArray()) ? 'selected':''}}>{{$permission->permission_name}}
                                    - {{$permission->label}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group"></div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">توضیحات کوتاه :</label>
                    <div class="col-sm-4">
                        <textarea class="form-control round-input" name="label" id="" cols="30"
                                  rows="5">{{$role->label}}</textarea>
                    </div>
                </div>

                <div class="text-center">
                    <button class="btn btn-round btn-primary">ویرایش</button>
                </div>
            </form>
        </div>
    </section>
@endsection
@section('script')
    <script src="/panel/js/bootstrap-select.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.permissions').selectpicker();
        })
    </script>
@endsection

resources/views/Panel/Roles/NewRole.blade.php
@extends('layouts.panel-master')
@section('title','افزودن سمت')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            افزودن سمت جدید
        </header>
        <div class="panel-body">
            <form class="form-horizontal tasi-form" method="POST" action="{{route('roles.store')}}"
                  enctype="multipart/form-data">
                {{csrf_field()}}
                @include('errors.errors')
                <div class="form-group">
                    <label class="col-sm-2 control-label">عنوان سمت :</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control round-input" name="role_name"
                               value="{{old('role_name')}}">
                    </div>

                    <label class="col-sm-2 control-label"> دسترسی ها :</label>
                    <div class="col-sm-4">
                        <select name="permissions[]" class="form-control round-input permissions" multiple>
                            <option value="0" disabled>انتخاب کنید ...</option>
                            @foreach($permissions as $permission)
                                <option value="{{$permission->id}}">{{$permission->permission_name}}
                                    - {{$permission->label}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group"></div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">توضیحات کوتاه :</label>
                    <div class="col-sm-4">
                        <textarea class="form-control round-input" name="label" id="" cols="30"
                                  rows="5">{{old('label')}}</textarea>
                    </div>
                </div>

                <div class="text-center">
                    <button class="btn btn-round btn-primary">ذخیره</button>
                </div>
            </form>
        </div>
    </section>
@endsection
@section('script')
    <script src="/panel/js/bootstrap-select.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.permissions').selectpicker();
        })
    </script>
@endsection

resources/views/Panel/Roles/RoleList.blade.php
@extends('layouts.panel-master')
@section('title','لیست سمت ها')
@section('content')
    <!-- page start-->
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                لیست سمت ها
                <a href="{{route('roles.create')}}" class="pull-left btn-sm btn-default">سمت جدید</a>
            </header>
            <div class="table-responsive">
                <table class="table table-striped table-advance table-hover">
                    <thead>
                    <tr>
                        <th><i class="icon-list"></i></th>
                        <th>عنوان سمت </th>
                        <th><i class="icon-file-text"></i> توضیحات کوتاه </th>
                        <th>تاریخ ایجاد</th>
                        <th>تاریخ بروزرسانی</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @php($i=1)
                    @foreach($roles as $role)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$role->role_name}}</td>
                            <td><a href="#">{{$role->label}}</a></td>
                            <td>{{jdate($role->created_at)->format('%A, %d %B %y')}}</td>
                            <td class="hidden-phone">{{jdate($role->updated_at)->format('%A, %d %B %y')}}</td>
                            <td>
                                <a href="{{route('roles.edit',['role'=>$role->id])}}"
                                   class="btn btn-primary btn-xs"><i
                                            class="icon-pencil"></i></a>
                                <form action="{{route('roles.destroy',['role'=>$role->id])}}" method="POST"
                                      style="display: inline">
                                    {{csrf_field()}}
                                    {{method_field('DELETE')}}
                                    <button class="btn btn-danger btn-xs"><i class="icon-trash "></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            {{$roles->links()}}
        </section>
    </div>
    <!-- page end-->

    <!-- js placed at the end of the document so the pages load faster -->

    <!--script for this page only-->
    <script src="/Panel/js/dynamic-table.js"></script>
@endsection